### Feature Engineering

In [4]:
# Import Libraries
import sys
from pathlib import Path
import pandas as pd

sys.path.insert(0, str(Path.cwd().parent.resolve()))
from src.features import engineer_features

In [5]:
# load the dataset
train = pd.read_csv("../data/processed/cleaned_train.csv")
test = pd.read_csv("../data/raw/Test.csv")

In [7]:
print()

import warnings
warnings.filterwarnings("ignore")

# Engineer feature
engineered_train = engineer_features(train)
engineered_test = engineer_features(test)

#### Verify

In [8]:
engineered_train.shape

(1821, 274)

In [10]:
print()
engineered_train.head()

,ID,label,VH_01,VV_01,blue_01,green_01,nir_01,nira_01,re1_01,re2_01,...,blue_cv,green_cv,red_cv,nir_cv,nira_cv,re1_cv,re2_cv,re3_cv,swir1_cv,swir2_cv
0,ID_TR_NEW_XVGKFMLNRJ,0,-29.099645,-22.471573,1665,1719,1367,1270,1689,1416,...,0.106317,0.113156,0.168640,0.224327,0.221987,0.173971,0.220032,0.224760,0.052668,0.039091
1,ID_TR_NEW_GP8KNSWVP6,0,-19.470574,-10.752340,1579,1740,2245,2231,2060,2147,...,0.157223,0.147846,0.227311,0.439969,0.439632,0.152449,0.415184,0.449331,0.142339,0.185309
2,ID_TR_NEW_87X3957MVS,1,-20.964854,-8.792675,1850,2345,3664,3470,2935,3384,...,0.113061,0.118615,0.131019,0.415668,0.395088,0.215761,0.348707,0.355198,0.357262,0.243952
3,ID_TR_NEW_T4JMRPKHS3,0,-18.728208,-4.689202,1279,1297,1713,1698,1527,1531,...,0.068904,0.099704,0.084412,0.282836,0.294549,0.131793,0.267744,0.293490,0.174961,0.112847
4,ID_TR_NEW_2CTUQQ8KLU,0,-29.630941,-23.370157,1625,1741,1339,1258,1658,1362,...,0.100936,0.095922,0.137038,0.242281,0.210032,0.148927,0.194398,0.204061,0.080863,0.082188

In [11]:
print()
engineered_train.describe()

,label,VH_01,VV_01,blue_01,green_01,nir_01,nira_01,re1_01,re2_01,re3_01,...,blue_cv,green_cv,red_cv,nir_cv,nira_cv,re1_cv,re2_cv,re3_cv,swir1_cv,swir2_cv
count,1821.000000,1821.000000,1821.000000,1821.000000,1821.000000,1821.000000,1821.000000,1821.000000,1821.000000,1821.000000,...,1821.000000,1821.000000,1821.000000,1821.000000,1821.000000,1821.000000,1821.000000,1821.000000,1821.000000,1821.000000
mean,0.403624,-25.379836,-15.136799,1651.551345,1845.806150,2317.796266,2281.221856,2072.400329,2166.834157,2239.166392,...,0.135514,0.130426,0.171681,0.259799,0.268805,0.160948,0.242720,0.257375,0.224742,0.208069
std,0.490759,5.586461,5.703961,274.479438,353.859045,869.923999,870.483060,462.457760,729.486832,797.647072,...,0.071840,0.061337,0.081347,0.097651,0.102752,0.062965,0.086694,0.091618,0.146761,0.124082
min,0.000000,-48.143182,-31.912804,1070.000000,1094.000000,1011.000000,1005.000000,1038.000000,1004.000000,1012.000000,...,0.021237,0.030581,0.032288,0.035367,0.032941,0.028842,0.038983,0.038255,0.022721,0.022481
25%,0.000000,-29.510694,-20.761611,1454.000000,1613.000000,1475.000000,1382.000000,1737.000000,1518.000000,1517.000000,...,0.089710,0.091264,0.117051,0.188092,0.190026,0.119076,0.179474,0.191200,0.109928,0.106466
50%,0.000000,-23.945252,-13.290349,1627.000000,1815.000000,2333.000000,2326.000000,2067.000000,2147.000000,2221.000000,...,0.121380,0.118368,0.157173,0.265397,0.277103,0.151823,0.244400,0.257298,0.164216,0.187588
75%,1.000000,-21.090626,-10.872466,1814.000000,2081.000000,2897.000000,2851.000000,2377.000000,2678.000000,2766.000000,...,0.162581,0.153043,0.213056,0.329250,0.343190,0.189672,0.302683,0.321125,0.352461,0.287908
max,1.000000,-10.404720,6.227268,3070.000000,3788.000000,6722.000000,6528.000000,3865.000000,5518.000000,6369.000000,...,0.718004,0.589436,0.618621,0.653243,0.701011,0.582431,0.657109,0.657803,0.825144,0.713096

In [12]:
print()
engineered_train.isnull().sum().sum()

np.int64(0)

#### Save

In [13]:
engineered_train.to_csv(
    "../data/processed/featured_train.csv",
    index=False
)

engineered_test.to_csv(
    "../data/processed/featured_test.csv",
    index=False
)